# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Sveltekit CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
  run:
    working-directory: ./sveltekit

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SvelteKit setup
        uses: ./.github/actions/sveltekit-setup
      - name: Lint application
        run: pnpm lint

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SvelteKit setup
        uses: ./.github/actions/sveltekit-setup
      - name: Check application for errors
        run: pnpm check
        env:
          PUBLIC_SUPABASE_ANON_KEY: mock_key
          PUBLIC_SUPABASE_URL: http://mock_url

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SvelteKit setup
        uses: ./.github/actions/sveltekit-setup
      - name: Run unit tests
        run: pnpm test:coverage
        env:
          PUBLIC_SUPABASE_ANON_KEY: mock_key
          PUBLIC_SUPABASE_URL: http://mock_url

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SvelteKit setup
        uses: ./.github/actions/sveltekit-setup
      - name: Install playwright dependencies
        run: pnpm exec playwright install --with-deps chromium
      - name: Run playwright tests
        run: pnpm playwright test --browser chromium
        env:
          PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}
          PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
