# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: ./sveltekit/package-lock.json
    - run: npm ci
      working-directory: ./sveltekit
      
  lint:
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: ./sveltekit/package-lock.json
    - run: npm ci
      working-directory: ./sveltekit
    - run: npm run lint
      working-directory: ./sveltekit
      
  check:
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: ./sveltekit/package-lock.json
    - run: npm ci
      working-directory: ./sveltekit
    - run: npm run check
      working-directory: ./sveltekit
      
  test:
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: ./sveltekit/package-lock.json
    - run: npm ci
      working-directory: ./sveltekit
    - run: npx playwright install-deps chromium
      working-directory: ./sveltekit
    - run: npm test
      working-directory: ./sveltekit
      env: 
        PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}
        PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
